import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div>
      <Head>
        <title>Mutfakta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative flex h-screen w-screen flex-col items-center justify-center rounded-md bg-orange-300 pb-4">
        <div className="fixed top-4 left-4 h-10 w-10 bg-orange-600 bg-cover [mask-image:url('/img/menu.svg')]"></div>
        <Component {...pageProps} />
      </div>
    </div>
  );
}

export default MyApp;
